# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-22.04
    env:
      ImageOS: ubuntu22
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.14.5"
            otp: "25.3"
          - elixir: "1.15.8"
            otp: "26.2"
          - elixir: "1.16.3"
            otp: "26.2"
          - elixir: "1.17.3"
            otp: "27.1"
          - elixir: "1.18.1"
            otp: "27.1"
          - elixir: "1.19.1"
            otp: "27.1"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ matrix.elixir }}-otp-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ matrix.elixir }}-otp-${{ matrix.otp }}-
          ${{ runner.os }}-mix-
    - name: Check code format
      run: mix format --check-formatted
    - name: Install dependencies
      run: mix deps.get
    - name: Run Credo (lint)
      run: mix credo --strict
    - name: Run tests
      run: mix test
